name: Sidecar E2E tests

on:
  push:
    branches: [ main ]
    paths-ignore:
      - '**.md'
  pull_request:
    branches: [ main ]
    paths-ignore:
      - '**.md'

concurrency:
  group: e2e-tests-${{ github.ref }}-${{ github.workflow }}
  cancel-in-progress: true

jobs:
  run-e2e-sidecar-test-suite:
    strategy:
      matrix:
       kube-version:
       - "1.19"
       - "1.28"
    uses: ./.github/workflows/e2e.yaml
    with:
      testsuite_name: sidecar
      kube_version: ${{ matrix.kube-version }}
