run-name: "Run E2E ${{ inputs.testsuite_name }} test suite"
on:
  workflow_call:
    inputs:
      testsuite_name:
        description: "Name of the test suite to run"
        required: true
        type: string
      kube_version:
        description: "Kubernetes version to use"
        required: true
        type: string

jobs:
  e2e:
    runs-on: ubuntu-20.04
    steps:
      - name: "Check out code into the Go module directory"
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: "Set up Go"
        uses: actions/setup-go@v5
        with:
          go-version: "1.21"
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
        with:
          install: true
      - name: Cache Docker layers
        uses: actions/cache@v2
        with:
          path: /tmp/.buildx-cache
          key: e2e-${{ github.sha }}
          restore-keys: |
            e2e-
      - name: "Install KIND"
        run: ./hack/install/install-kind.sh
        shell: bash
      - name: "Install KUTTL"
        run: ./hack/install/install-kuttl.sh
        shell: bash
      - name: "Install gomplate"
        run: ./hack/install/install-gomplate.sh
        shell: bash
      - name: "Install dependencies"
        run: make install-tools
        shell: bash
      - name: "Run E2E ${{ inputs.testsuite_name }} test suite on ${{ inputs.kube_version }}"
        env:
          VERBOSE: "true"
          KUBE_VERSION: "${{ inputs.kube_version }}"
          DOCKER_BUILD_OPTIONS: "--cache-from	type=local,src=/tmp/.buildx-cache --cache-to type=local,dest=/tmp/.buildx-cache-new,mode=max --load"
        run: make run-e2e-tests-${{ inputs.testsuite_name }}
        shell: bash
        # Temp fix
        # https://github.com/docker/build-push-action/issues/252
        # https://github.com/moby/buildkit/issues/1896
      - name: Move cache
        run: |
          rm -rf /tmp/.buildx-cache
          mv /tmp/.buildx-cache-new /tmp/.buildx-cache
        shell: bash
